JESI-2870
jesims/url pull request #2
Opened 2019-08-23 06:45 UTC by axrs

[JESI-2870](https://jesims.atlassian.net/browse/JESI-2870)

2019-08-25 06:29 UTC, axrs reviewed
LGTM

2019-08-25 06:37 UTC, BadAlgorithm requested changes

2019-08-25 06:37 UTC, BadAlgorithm commented on CHANGELOG.md
> +* Anchors are now broken into `anchor` and `anchor-query`
Add tests to cover the scenario with an anchor with an empty query

2019-09-03 02:17 UTC, BadAlgorithm approved these changes

2019-09-03 03:36 UTC, AndreTheHunter approved these changes

2019-09-03 03:37 UTC, merged